<?php

namespace App\Filament\Resources;

use App\Filament\Resources\ZakatLedgerResource\Pages;
use App\Models\ZakatLedger;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class ZakatLedgerResource extends Resource
{
    protected static ?string $model = ZakatLedger::class;

    protected static string|\BackedEnum|null $navigationIcon = 'heroicon-o-book-open';

    protected static \UnitEnum|string|null $navigationGroup = 'Manajemen Zakat & Penyaluran';

    protected static ?string $navigationLabel = 'Buku Kas Zakat (Ledger)';

    protected static ?string $modelLabel = 'Buku Kas Zakat';

    protected static ?string $pluralModelLabel = 'Buku Kas Zakat';

    protected static ?int $navigationSort = 3;

    public static function canCreate(): bool
    {
        return false; // Auto-generated by system transactions
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime('d M Y, H:i')
                    ->sortable()
                    ->label('Tanggal & Waktu'),

                Tables\Columns\TextColumn::make('type')
                    ->badge()
                    ->formatStateUsing(fn (string $state): string => match ($state) {
                        'credit' => '🟢 Uang Masuk (+)',
                        'debit' => '🔴 Uang Keluar (-)',
                        default => $state,
                    })
                    ->color(fn (string $state): string => match ($state) {
                        'credit' => 'success',
                        'debit' => 'danger',
                        default => 'gray',
                    })
                    ->label('Jenis Transaksi'),

                Tables\Columns\TextColumn::make('amount')
                    ->money('IDR')
                    ->sortable()
                    ->weight('bold')
                    ->color(fn (ZakatLedger $record) => $record->type === 'credit' ? 'success' : 'danger')
                    ->label('Nominal (Rp)'),

                Tables\Columns\TextColumn::make('balance_after')
                    ->money('IDR')
                    ->sortable()
                    ->weight('bold')
                    ->label('Saldo Akhir Kas (Rp)'),

                Tables\Columns\TextColumn::make('description')
                    ->searchable()
                    ->wrap()
                    ->label('Keterangan Mutasi Kas'),
            ])
            ->defaultSort('created_at', 'desc')
            ->filters([
                Tables\Filters\SelectFilter::make('type')
                    ->options([
                        'credit' => 'Uang Masuk (Credit)',
                        'debit' => 'Uang Keluar (Debit)',
                    ])
                    ->label('Filter Jenis Transaksi'),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListZakatLedgers::route('/'),
        ];
    }
}
